#!/usr/bin/env zsh

here="$(dirname $0)"
filter_index=$here/../filter/src/index.js

in_file=$here/../samples/in-1.md
out_file=$here/../samples/out-1.docx

pandoc -f markdown -t docx --filter $filter_index $in_file -o $out_file

